"""
ClickUp integration — posts a daily trading summary as a task in a ClickUp list.

Setup:
  1. Add to .env:
       CLICKUP_API_TOKEN=pk_xxxxx
       CLICKUP_LIST_ID=12345678
  2. The LIST_ID is found in the ClickUp URL: app.clickup.com/xxx/v/l/{LIST_ID}

Each EOD run creates a new task in the list titled:
  "Trading Summary — {date} | {outcome} | P&L: ${pnl:+,.2f}"

With a description body covering:
  - Trades taken / skipped
  - Session P&L
  - Market regime
  - Top lesson from today
  - Bias for tomorrow
"""

import json
import logging
import os
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Optional

import requests
from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parent.parent / ".env")
log = logging.getLogger(__name__)

_CLICKUP_BASE = "https://api.clickup.com/api/v2"
_TIMEOUT = 10

_EXEC_LOG     = Path(__file__).parent.parent / "execution_log.json"
_CONTEXT_FILE = Path(__file__).parent.parent / "context" / "market_context.md"
_LESSONS_FILE = Path(__file__).parent.parent / "journal" / "lessons.md"


def _get_credentials() -> tuple[Optional[str], Optional[str]]:
    token   = os.environ.get("CLICKUP_API_TOKEN")
    list_id = os.environ.get("CLICKUP_LIST_ID")
    return token, list_id


def _last_lesson_snippet() -> str:
    """Extract the most recent lesson entry from lessons.md."""
    if not _LESSONS_FILE.exists():
        return "No lessons recorded yet."
    try:
        text = _LESSONS_FILE.read_text(encoding="utf-8")
        # Find last "## Session:" heading
        sections = text.split("## Session:")
        if len(sections) > 1:
            return sections[-1].strip()[:600]
    except Exception:
        pass
    return "Could not read lessons."


def _context_bias() -> str:
    """Extract the bias line from market_context.md."""
    if not _CONTEXT_FILE.exists():
        return "Context not available."
    try:
        text = _CONTEXT_FILE.read_text(encoding="utf-8")
        for line in text.splitlines():
            if "Bias" in line and ("Bullish" in line or "Bearish" in line or "Neutral" in line):
                return line.strip().lstrip("#").strip()
    except Exception:
        pass
    return "See market_context.md"


def _last_execution() -> dict:
    if not _EXEC_LOG.exists():
        return {}
    try:
        return json.loads(_EXEC_LOG.read_text(encoding="utf-8"))
    except Exception:
        return {}


def build_summary(
    session_pnl: float = 0.0,
    trades_taken: int = 0,
    extra_notes: str = "",
) -> dict:
    """
    Build the ClickUp task payload for today's session summary.
    Returns a dict ready to POST to the ClickUp API.
    """
    today = date.today().isoformat()
    last_exec = _last_execution()
    symbol = last_exec.get("symbol", "—")
    action = last_exec.get("action", "—")
    fill = last_exec.get("fill_price")
    stop = last_exec.get("stop_order_id")

    outcome = "WIN" if session_pnl > 0 else "LOSS" if session_pnl < 0 else "FLAT"
    title = f"Trading Summary — {today} | {outcome} | P&L: ${session_pnl:+,.2f}"

    body = f"""## Daily Trading Summary — {today}

### Session P&L
**${session_pnl:+,.2f}** ({outcome}) | Trades taken: {trades_taken}

### Last Execution
- Symbol: {symbol}
- Action: {action}
- Fill price: ${fill if fill else 'N/A'}
- Stop order: {'Placed' if stop else 'None'}

### Market Bias for Tomorrow
{_context_bias()}

### Today's Lesson
{_last_lesson_snippet()}

{('### Notes\n' + extra_notes) if extra_notes else ''}

---
*Generated by autonomous trading agent at {datetime.now(tz=timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*
"""

    return {
        "name": title,
        "description": body,
        "status": "complete",
        "priority": 3,   # normal
        "due_date": int(datetime.now(tz=timezone.utc).timestamp() * 1000),
        "tags": ["trading", outcome.lower(), today],
    }


def post_daily_summary(
    session_pnl: float = 0.0,
    trades_taken: int = 0,
    extra_notes: str = "",
) -> bool:
    """
    Post a daily summary task to ClickUp.
    Returns True on success, False on failure or missing credentials.
    """
    token, list_id = _get_credentials()
    if not token or not list_id:
        log.warning(
            "ClickUp credentials not set — add CLICKUP_API_TOKEN and CLICKUP_LIST_ID to .env"
        )
        return False

    payload = build_summary(session_pnl, trades_taken, extra_notes)

    try:
        resp = requests.post(
            f"{_CLICKUP_BASE}/list/{list_id}/task",
            headers={
                "Authorization": token,
                "Content-Type": "application/json",
            },
            json=payload,
            timeout=_TIMEOUT,
        )
        resp.raise_for_status()
        task = resp.json()
        log.info(
            "ClickUp task created: '%s' → %s",
            payload["name"],
            task.get("url", task.get("id")),
        )
        return True
    except requests.HTTPError as e:
        log.error("ClickUp API error: %s — %s", e, e.response.text if e.response else "")
        return False
    except Exception as e:
        log.error("ClickUp post failed: %s", e)
        return False
